--- #YAML:1.0
name:                autobox-Core
version:             0.4
abstract:            Perl built-in functions exposed as methods in primitive types
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    autobox:                       0.11
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Scott Walters scott@slowass.net
