--- #YAML:1.0
name:               autobox-Core
version:            1.23
abstract:           Provide core functions to autoboxed scalars, arrays and hashes.
author:
    - Scott Walters scott@slowass.net
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  6.46
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    autobox:     2.71
    Test::More:  0.88
resources:
    bugtracker:  http://github.com/scrottie/autobox-Core/issues
    repository:  http://github.com/scrottie/autobox-Core
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
