--- #YAML:1.0
name:               autobox-Core
version:            1.2
abstract:           Core functions exposed as methods in primitive types
author:
    - Scott Walters scott@slowass.net
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    autobox:  0.11
resources:
    bugtracker:  http://github.com/scrottie/autobox-Core/issues
    repository:  http://github.com/scrottie/autobox-Core
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
